Linear Regression Using Normal Equation (easy)
Write a Python function that performs linear regression using the normal equation. The function should take a matrix X (features) and a vector y (target) as input, and return the coefficients of the linear regression model. Round your answer to four decimal places, -0.0 is a valid result for rounding a very small number.

Example:
        input: X = [[1, 1], [1, 2], [1, 3]], y = [1, 2, 3]
        output: [0.0, 1.0]
        reasoning: The linear model is y = 0.0 + 1.0*x, perfectly fitting the input data.

Linear Regression Using the Normal Equation
Linear regression aims to model the relationship between a scalar dependent variable 
 and one or more explanatory variables (or independent variables) 
. The normal equation provides an analytical solution to finding the coefficients 
 that minimize the cost function for linear regression. Given a matrix 
 (with each row representing a training example and each column a feature) and a vector 
 (representing the target values), the normal equation is:
    theta = (XT* X)**(-1)* XT * y
Where:
 XT is the transpose of X
,
(XT* X)**(-1) is the inverse of the matrix  XT*X
,
 y is the vector of target values.
**Things to note**: 
This method does not require any feature scaling, and there's no need to choose a learning rate. However, computing the inverse of XT*X
 can be computationally expensive if the number of features is very large.
Practical Implementation
A practical implementation involves augmenting 
 with a column of ones to account for the intercept term and then applying the normal equation directly to compute Theta
.

In [2]:
X = [[1, 1], [1, 2], [1, 3]]
y = [1, 2, 3]

In [3]:
import numpy as np
X = np.array(X)
y = np.array(y).reshape(-1, 1)


In [8]:
print(X, X.shape)

[[1 1]
 [1 2]
 [1 3]] (3, 2)


In [5]:
y

array([[1],
       [2],
       [3]])

In [6]:
X_transpose = X.T
X_transpose

array([[1, 1, 1],
       [1, 2, 3]])

In [7]:
X_transpose.dot(X)

array([[ 3,  6],
       [ 6, 14]])

In [9]:
np.linalg.inv(X_transpose.dot(X))

array([[ 2.33333333, -1.        ],
       [-1.        ,  0.5       ]])

In [11]:
np.linalg.inv(X_transpose.dot(X)).dot(X_transpose)

array([[ 1.33333333,  0.33333333, -0.66666667],
       [-0.5       ,  0.        ,  0.5       ]])

In [12]:
theta = np.linalg.inv(X_transpose.dot(X)).dot(X_transpose).dot(y)
theta

array([[-1.77635684e-15],
       [ 1.00000000e+00]])

In [13]:
theta = np.round(theta, 4).flatten().tolist()
theta

[-0.0, 1.0]